# Site settings
title: Polyamide Blog
email: debanjan.basu@tu-clausthal.de
author: Debanjan Basu
description: "Mostly about productivity, physics and procrastination"
baseurl: ""
url: "http://d3banjan.github.io"
category-list: [ "all" , "journal" , "software" , "physics" , "literary" , "opinions" , "none" ]
#google_analytics: TODO 
# Build settings
markdown: kramdown
permalink: pretty
#paginate: 10
#kramdown options 
kramdown:
  input: GFM
